version: "3.5"

services:
  lint_service:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: make lints
  test_service:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: pytest
  run_core_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: python pubg/fetch-data.py